# -*- coding: utf-8 -*-
"""task_2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5HDzLtXmG4ZWWQnHQ_hZLYXFwC-cMsD
"""

from random import randint
n = int(input("Введи количество элементов"))
lst = []
for i in range(n):
  lst.append (randint(0,100))

def min(lst):
  min_n = lst[0]
  for i in lst:
    if i < min_n:
      min_n = i
    i+=1
  return min_n

def max(lst):
  max_n = lst[0]
  for i in lst:
    if i > max_n:
      max_n = i
    i+=1
  return max_n

 
print(lst)
print(f' min = {min(lst)}, max = {max(lst)}')