# -*- coding: utf-8 -*-
"""task_2.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eBZSKCDDz94JQVtx5zBpIb3pkEw8fsT
"""

months = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
month = int(input("Введи номер месяца"))
def quarter_of(month):
  if 1 <= month <= 3:
   return f'Месяц {month}({months[month-1]}) является частью первого квартала'
  elif 4 <= month <= 6:
   return f'Месяц {month}({months[month-1]}) является частью второго квартала'
  elif 7 <= month <= 9:
   return f'Месяц {month}({months[month-1]}) является частью третьего квартала'
  elif 10 <=month <= 12:
   return f'Месяц {month}({months[month-1]}) является частью четвертого квартала'
  else:
    print ("Такого месяца нет, введите число от 1 до 12")

print(quarter_of(month))