# -*- coding: utf-8 -*-
"""task_2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Wm39tUUSRO_L8Be-14Yoxzbb8IGfxs9
"""

#numbers = {'1:one', '2:two', '3:three', '4:four', '5:five', '6:six', '7:seven', '8:eight', '9:nine' }

names = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']
number = int(input("Введи число"))
def switch_it_up(number):
 try:
  return f' {number} => {names[number-1]}'
 except IndexError:
  return None

print (switch_it_up(number))