# -*- coding: utf-8 -*-
"""task_2.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f75H69m5stCVs2aInH-SCT5-pWA6OSaX
"""

#Пункт А
s = input ('Введите строку' )
import re
def remove_exclamation_marks(s):
 return re.sub('!','',s)

print (remove_exclamation_marks(s))

#Пункт Б

s = input ('Введи строку')
def remove_last_em(s):
  i = 0
  while i<1 and s[-1] == '!':
    s = s [:-1]
    i += 1
    return s
print (remove_last_em(s))